services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: sidecar
      POSTGRES_PASSWORD: sidecar123
      POSTGRES_DB: SideCarDb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sidecar-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sidecar -d SideCarDb"]
      interval: 5s
      timeout: 5s
      retries: 5

  main-api:
    build:
      context: .
      dockerfile: SideCar.API/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - sidecar-network

  moto:
    image: motoserver/moto:latest
    ports:
      - "5555:5555"
    environment:
      - MOTO_PORT=5555
    networks:
      - sidecar-network
  init-s3:
    image: amazon/aws-cli:latest
    depends_on:
      - moto
    entrypoint: /bin/sh
    command: /init-aws.sh
    environment:
      - AWS_ACCESS_KEY_ID=testing
      - AWS_SECRET_ACCESS_KEY=testing
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - ./EmailTemplates:/EmailTemplates
      - ./init-aws.sh:/init-aws.sh
    networks:
      - sidecar-network

  sidecar-worker:
    build:
      context: .
      dockerfile: SideCar.Worker/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      main-api:
        condition: service_started
      init-s3:
        condition: service_completed_successfully
          
    networks:
      - sidecar-network
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: '1G'
        reservations:
          cpus: '0.25'
          memory: '500M'

  nginx:
    image: nginx:alpine
    ports:
      - "5072:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - main-api
    networks:
      - sidecar-network

  sidecar-authen:
    build:
      context: .
      dockerfile: SideCar.Authen/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:5001
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - sidecar-network
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '256M'

  redis:
    image: redis:7-alpine
    ports:
      - "6381:6379"
    networks:
      - sidecar-network
      
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - sidecar-network

networks:
  sidecar-network:
    driver: bridge

volumes:
  postgres_data:
